version: "3.4"
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "nginx_data:/usr/share/nginx/html"
    ports:
      - "3000:80"
    restart: unless-stopped
volumes:
  nginx_data:
  